### ISSUE TITLE
`==` vs `is` for String

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#29]
The [Types](https://pythoninchemistry.org/intro_python_chemists/basics/types.html#Logical-operators) section says that it is preferred to use `is` and `is not` instead of `==` and `!=` in string comparison. This is [**a lot** more nuanced](https://stackoverflow.com/questions/47778889/pylint-complains-about-comparing-a-string-to-a-literal-with-is/47778970#47778970) than I first thought so it is probably best to remove it completely.

**Comment by bjmorgan** [comment]
What was the motivation for recommending `is` over `==`?

**Comment by bjmorgan** [comment]
> Despite the fact that it is possible to apply the == and != operators to strings, it is stylistically frowned upon.

[citation needed](https://xkcd.com/285/)

**Comment by arm61** [comment]
This was me not fully investigating why [pylint](https://stackoverflow.com/questions/14247373/python-none-comparison-should-i-use-is-or) was making me change `==` to `is` when comparing strings 

https://www.python.org/dev/peps/pep-0008/#programming-recommendations

**Comment by bjmorgan** [comment]
I think we need to be careful about emphasising a specific coding style, except in a dedicated "style & readability" section, and of course, implicitly through our own code examples. There are already too many comments online with people saying code is "wrong" because it's not PEP8. And points like the one above only make sense once you have a much more detailed understanding of 1. how Python works under the hood, and 2. where likely bugs can appear and why certain coding styles might prevent these.

**Comment by arm61** [comment]
Agreed, hence I will pull that bit.

**Comment by arm61** [comment]
dealt with in #31
