### ISSUE TITLE
Should objects and methods be included in basics?

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#46]
@bjmorgan raised the idea that the concept of *objects* having *methods* should be introduced immediately after functions, without necessarily explaining classes.

This issue is to chat about that.

**Comment by j-m-dean** [comment]
Pros: It would make the optimisation section more readable as it would explain solution.x and solution.fun. , as well as, most likely, some of the good practice chapter. It is probably a nice thing just to mention. Build with exposure from examples in the good practise and data work sections and then property introduce it in the advanced chapter.

Cons: Thinking of chemistry examples that do not introduce classes may be tricky. It may be too much, too fast for students and confuse them.

**Comment by arm61** [comment]
A potential way round the first con would be to make a custom class that is like 

```
# in a file called elements.py

class Carbon:
    def __init__(self):
        self.atomic_number = 6
        self.electrons = 6
    def ionise(ionisation):
        self.electrons += ionisation
```

In the book the student would `import elements` then do like 

```
carbon = Carbon()
carbon_anion = Carbon()
carbon_anion.ionise(-1)
```

**Comment by RMeli** [comment]
This is an interesting discussion. When I learned programming I followed [C++ How to Program](https://deitel.com/c-plus-plus-how-to-program-10-e/), where the authors introduce classes, objects, and member functions even before control statements and functions (see [C++ How to Program - TOC](https://deitel.com/wp-content/uploads/2019/11/c-plus-plus-how-to-program-10-table-of-contents.pdf)). That was quite extreme (and I struggled with most concepts at first), but since most libraries are based on OOP, a short introduction in`Basics` might be beneficial. This will help to better understand simple things like `mystring.upper()` (already used in `1.1 Types`) and `myarray.shape` (that will probably appear in `1.3 Numpy Arrays`).

**Comment by arm61** [comment]
I think there is definitely utility to introducing class methods, perhaps as "object methods" later in the `Basics` section. 

However, I think that introducing everything to do with classes is a bit over the top (and very C++ esc). Remember that the aim of the book is to give chemists the tool of programming for chemistry tasks, you don't need to be able to do OOP to fit a straight line to Arrhenius data and make a nice plot of it.
